// These are games meant to misdirect the player. They will populate the dropdown but won't ever be the games used in the puzzle
export const dummyGames: string[] = [
  'SEGA AGES G-LOC: Air Battle',
  'Foul Play',
  'The Last of Us Part I',
  'Ace Combat 5: The Unsung War',
  'Ace Combat 6: Fires of Liberation',
  'Alphadia Genesis',
  'Warhammer Quest',
  'flower',
  'ZEN Pinball 2',
  'Long Live The Queen',
  'Samurai Gunn',
  'Malicious Fallen',
  'Bridge Constructor',
  "Wooden Sen'SeY",
  'Gomo',
  'Batman: Arkham Asylum',
  'Batman: Arkham City',
  'Batman: Arkham Origins',
  "Adventure Time: Explore the Dungeon Because I DON'T KNOW!",
  'Kentucky Route Zero',
  'Cannon Brawl',
  'Electronic Super Joy',
  'Castlevania: Lords of Shadow',
  'Tetrobot and Co.',
  'Just Dance 2014',
  'Ultratron',
  'Type:Rider',
  'Redshirt',
  'Unholy Heights',
  'Kid Tripp',
  'Mitsurugi Kamui Hikae',
  'Volgarr the Viking',
  'The Wolf Among Us: Episode 1 - Faith',
  'Angry Video Game Nerd Adventures',
  'Deadpool',
  'SimCity: Cities of Tomorrow Expansion Pack',
  'Gravity Badgers',
  'Disney DuckTales Remastered',
  'Ironclad Tactics',
  'Escape Plan',
  'Sonic: Lost World',
  'The Journey Down: Chapter One',
  'Kingdom Rush Frontiers',
  'Knock-Knock',
  'Journey of a Roach',
  'Speedball 2 HD',
  'Putty Squad',
  'Zumba Fitness World Party',
  'Solar Flux',
  'Rugby World Cup 2015',
  'The Dark Eye: Memoria',
  'Chivalry: Deadliest Warrior',
  'Monster Loves You',
  'Goodbye Deponia',
  'Cookie Clicker',
  'Gas Guzzlers Extreme',
  'Sorcery Saga: Curse of the Great Curry God',
  'Ms. Splosion Man',
  'Urban Trial Freestyle',
  'Game Dev Tycoon',
  'If My Heart Had Wings',
  'Shadowrun Returns',
  'Skulls Of The Shogun: Bone-A-Fide Edition',
  'The Room Two',
  'Guilty Gear XX Accent Core Plus R',
  'Megabytes Punch',
  'Project X Zone',
  'Nicole',
  'Ravensword: Shadowlands',
  "Picdun 2: Witch's Curse",
  'The Pinball Arcade',
  'Dust: An Elysian Tail',
  'Mario and Donkey Kong: Minis on the Move',
  'Cloudberry Kingdom',
  'BIT.TRIP FATE',
  'Kingdom Tales',
  'Ghost: Elisa Cameron',
  'Fate Of The Pharaoh',
  'Farm for your Life',
  'Draw a Stickman: EPIC',
  'Lost Odyssey',
  'Contagion',
  'The Legend of Zelda: Oracle of Seasons',
  'The Legend of Zelda: Oracle of Ages',
  'Runner2: Future Legend of Rhythm Alien',
  'A Walk in the Dark',
  'ACA NEOGEO Real Bout Fatal Fury',
  'Sword of the Stars: The Pit',
  'Chain Blaster',
  'Rage of the Gladiator',
  'The Shivah: Kosher Edition',
  'Magrunner: Dark Pulse',
  'Splinter Cell: Blacklist',
  'Old School RuneScape',
  'FORCED: Slightly Better Edition',
  'Forced',
  'Shelter',
  'Teleglitch: Die More Edition',
  'Alien Breed',
  'The Denpa Men 2: Beyond the Waves',
  "Joe Dever's Lone Wolf",
  'Battle Worlds: Kronos',
  'Defense Grid 2',
  'Ethan: Meteor Hunter',
  'Professor Layton and the Azran Legacy',
  'Killer Instinct',
  'The LEGO Movie Videogame',
  'Among the Sleep',
  'Kinect Sports Rivals',
  'Crimsonland',
  'NHL 15',
  "D4: Dark Dreams Don't Die",
  'Disney Infinity 2.0 Edition',
  'Styx: Master of Shadows',
  'Whispering Willows',
  'Risen 3: Titan Lords',
  'Sleeping Dogs: Definitive Edition',
  'Tomodachi Life',
  'Sacred 3',
  'The Wolf Among Us: Episode 3 - A Crooked Mile',
  "The Walking Dead: Season Two Episode 3 - In Harm's Way",
  'The Fall',
  'CounterSpy',
  'The Last Tinker: City of Colors',
  'Lifeless Planet',
  'The Legend of Korra',
  'Persona Q: Shadow of the Labyrinth',
  'Theatrhythm Final Fantasy: Curtain Call',
  'WildStar',
  'Nidhogg',
  'The Walking Dead: Season Two Episode 5 - No Going Back',
  'Gauntlet',
  'Transformers: Rise of the Dark Spark',
  'Super Time Force',
  'Xeodrifter',
  'Jazzpunk',
  'Stranger of Sword City',
  'Natural Doctrine',
  'BioShock Infinite: Burial at Sea - Episode Two',
  "The Wolf Among Us: Episode 4 - In Sheep's Clothing",
  'The Walking Dead: Season Two Episode 4 - Amid the Ruins',
  'The Incredible Adventures of Van Helsing II',
  'Costume Quest 2',
  'The Wolf Among Us: Episode 5 - Cry Wolf',
  'DG2: Defense Grid 2',
  'Warriors Orochi 3 Ultimate',
  'GRID Autosport',
  'Gods Will Be Watching',
  'Abyss Odyssey',
  "Strike Suit Zero: Director's Cut",
  'Pure Pool',
  'Blackguards',
  'Infinity Runner',
  'Endless Legend',
  'Tales of Hearts R',
  "Shantae: Risky's Revenge - Director's Cut",
  'MouseCraft',
  "Assassin's Creed Rogue",
  'Tower of Guns',
  'Shadowgate',
  'Entwined',
  'Stealth Inc 2: A Game of Clones',
  'Pushmo World',
  'Always Sometimes Monsters',
  'Castlevania: Lords of Shadow 2',
  'Farming Simulator 15',
  'Hearthstone: Heroes of Warcraft',
  'SMITE',
  "QUBE: Director's Cut",
  'Sunless Sea',
  'One Piece: Unlimited World Red',
  'Disgaea 4: A Promise Revisited',
  'OlliOlli',
  'Chariot',
  "Schrodinger's Cat and the Raiders of the Lost Quark",
  'The Binding of Isaac: Rebirth',
  'Guilty Gear Xrd -SIGN-',
  "Don't Starve: Console Edition",
  'NES Remix 2',
  'Road Not Taken',
  'Neverending Nightmares',
  'Rollers of the Realm',
  'Back to Bed',
  'MLB 14: The Show',
  'Samurai Warriors 4',
  'ETHER One',
  'Dynasty Warriors 8: Xtreme Legends Complete Edition',
  'Loadout',
  'The Golf Club',
  'Ultra Street Fighter IV',
  'Unepic',
  'Dead Rising 3: Apocalypse Edition',
  'Moebius: Empire Rising',
  'Blue Estate',
  'One Piece: Romance Dawn',
  'Kalimba',
  'Just Dance 2015',
  'Elliot Quest',
  'Hyperdevotion Noire: Goddess Black Heart',
  'Pix the Cat',
  'Worms Battlegrounds',
  'StarCraft II: Legacy of the Void',
  'Tearaway Unfolded',
  'ScreamRide',
  'Her Story',
  'Pro Evolution Soccer 2016',
  'Life is Strange: Episode 4 - Dark Room',
  'Game of Thrones: Episode Three - The Sword in the Darkness',
  'Volume',
  'Crypt of the NecroDancer',
  'Assault Android Cactus',
  'Naruto Shippuden: Ultimate Ninja Storm 4',
  'Total War: Attila',
  'The Swindle',
  'WWE 2K16',
  'Citizens of Earth',
  'Journey',
  'Tales from the Borderlands - Season One',
  'Galak-Z',
  "Wasteland 2: Director's Cut",
  'Game of Thrones: Episode Four - Sons of Winter',
  'Republique Remastered',
  'Dead or Alive 2',
  'Dead or Alive 3',
  'Dead or Alive 4',
  'Dead or Alive 5',
  'Dragon Ball: Xenoverse',
  'Rory McIlroy PGA Tour',
  'Mario Tennis: Ultra Smash',
  'The Deer God',
  'Helldivers',
  'Warhammer: End Times - Vermintide',
  'TEMBO THE BADASS ELEPHANT',
  'Animal Crossing Happy Home Designer',
  'Downwell',
  'The Book of Unwritten Tales 2',
  'The Park',
  'Invisible Inc.',
  'Disgaea 5: Alliance of Vengeance',
  'Broforce',
  'Party Hard',
  'Kholat',
  "Tony Hawk's Pro Skater 5",
  'Bloodborne: The Old Hunters',
  'Tales From The Borderlands: Episode Two - Atlas Mugged',
  'Hand of Fate',
  'Devil May Cry 4: Special Edition',
  'Adventures of Pip',
  'Zombie Army Trilogy',
  'Earth Defense Force 4.1: The Shadow of New Despair',
  'F1 2015',
  'Chibi-Robo!: Zip Lash',
  'Godzilla',
  'Borderlands: The Handsome Collection',
  'God of War III Remastered',
  'State of Decay: Year One Survival Edition',
  'Divinity: Original Sin - Enhanced Edition',
  'Homeworld Remastered Collection',
  'Kerbal Space Program',
  'Lost Dimension',
  'Gal*Gun: Double Peace',
  'Etrian Odyssey 2 Untold: The Fafnir Knight',
  'NHL 16',
  'PSYCHO-PASS: Mandatory Happiness',
  'Ironcast',
  'ZOMBI',
  'OlliOlli2: Welcome to Olliwood',
  'Broken Age',
  'Grow Home',
  'Victor Vran',
  'Game of Thrones: Episode Five - A Nest of Vipers',
  'Hard West',
  "Sid Meier's Starships",
  'Sword Coast Legends',
  'I Am Bread',
  'Game of Thrones: Episode Six - The Ice Dragon',
  'Pokémon X and Y',
  'Pokémon Omega Ruby and Alpha Sapphire',
  'Pokémon Sword and Shield',
  'Pokémon Scarlet and Violet',
  'Magicka 2',
  'Tales from the Borderlands: Episode Five - The Vault of the Traveler',
  'Heroes of the Storm',
  'NBA 2K16',
  'Boxboy',
  'Etrian Mystery Dungeon',
  'Resident Evil: Revelations 2 - Episode 1: Penal Colony',
  'Utawarerumono: Mask of Deception',
  'Onechanbara Z2: Chaos',
  'One Piece: Pirate Warriors 3',
  'Mario vs. Donkey Kong: Tipping Stars',
  'FAST Racing Neo',
  'MLB 15: The Show',
  'Blackguards 2',
  'Devil Survivor 2: Record Breaker',
  'Rebel Galaxy',
  'Massive Chalice',
  'Dynasty Warriors 8 Empires',
  'Toren',
  'Coffin Dodgers',
  'Story of Seasons',
  'Blues and Bullets - Episode 1',
  'Tachyon Project',
  'Dropsy',
  'Apotheon',
  'Planet Coaster',
  'Kirby: Planet Robobot',
  'This Is the Police',
  'Metroid Prime: Federation Force',
  'The Town of Light',
  'Umbrella Corps',
  'Mario & Luigi Paper Jam',
  'WWE 2K17',
  'Tokyo Mirage Sessions #FE',
  'Monster Hunter Stories',
  'Song of the Deep',
  'Dead by Daylight',
  'SUPERHOT (VR)',
  'The Turing Test',
  'NBA 2K17',
  'The Walking Dead: Michonne - Episode 1: In Too Deep',
  'Star Ocean: Integrity and Faithlessness',
  'Syberia 3',
  'Teenage Mutant Ninja Turtles: Mutants in Manhattan',
  'Thumper',
  'Bravely Second: End Layer',
  'Serial Cleaner',
  'TrackMania Turbo',
  'Aragami',
  'Amplitude HD',
  'Hitman - Episode 2: Sapienza',
  'NHL 17',
  'EA Sports UFC 2',
  'Stories: The Path of Destinies',
  'Mantis Burn Racing',
  'God Eater 2: Rage Burst',
  'Rez Infinite',
  'Resident Evil 4',
  'Gravity Rush Remastered',
  "Assassin's Creed Chronicles: India",
  'Shu',
  'Yo-Kai Watch 2',
  'Day of the Tentacle Remastered',
  'PAC-MAN Championship Edition 2',
  'Shiren the Wanderer: The Tower of Fortune and the Dice of Fate',
  'Final Fantasy Explorers',
  'EARTHLOCK',
  'Ori and the Blind Forest: Definitive Edition',
  'Digimon Story: Cyber Sleuth',
  'Clustertruck',
  'Sword Art Online: Hollow Realization',
  'Nights of Azure',
  'Maize',
  'Valkyria Chronicles Remastered',
  'Dragon Quest IV',
  'Dragon Quest V',
  'Dragon Quest VI',
  'Dragon Quest VII',
  'Dragon Quest VIII',
  'Dragon Quest IX',
  'Dragon Quest X',
  "Tom Clancy's Rainbow Six Siege",
  "Tom Clancy's Rainbow Six: Vegas",
  "Tom Clancy's Ghost Recon Phantoms",
  'Fallout 4: Far Harbor',
  'Homeworld: Deserts of Kharak',
  'Alienation',
  'Hyrule Warriors Legends',
  'The Silver Case',
  'Fairy Fencer F: Dark Advent Force',
  'Steins;Gate 0',
  'Momodora: Reverie Under the Moonlight',
  'Death Road to Canada',
  'Bound',
  'Tharsis',
  'Necropolis',
  'Shadwen',
  'Stellaris',
  'Rive',
  'SAMURAI WARRIORS: Spirit of Sanada',
  'Black Desert Online',
  'Project X Zone 2',
  'Mother Russia Bleeds',
  'Megadimension Neptunia VII',
  'The Longest Five Minutes',
  'Fallout 4: Automatron',
  'Shadow of the Beast',
  "Sherlock Holmes: The Devil's Daughter",
  'Ghostbusters',
  'That Dragon, Cancer',
  'This War of Mine: The Little Ones',
  'Lumo',
  'Just Dance 2017',
  'Masquerada: Songs and Shadows',
  'Space Hulk: Deathwing',
  'Shin Megami Tensei IV: Apocalypse',
  'Atelier Sophie: The Alchemist of the Mysterious Book',
  'Duke Nukem 3D: World Tour - 20th Anniversary Edition',
  'Until Dawn: Rush of Blood (VR)',
  'Valley',
  'Grow Up!',
  'One Piece: Burning Blood',
  'The Walking Dead: Michonne - Episode 2: Give No Shelter',
  "Dead Rising 4: Frank's Big Package",
  'Valkyria Revolution',
  'Dragon Quest Heroes 2',
  'L.A. Noire Remastered',
  'Batman: The Enemy Within - Episode 1',
  'Bulletstorm: Full Clip Edition',
  'ELEX',
  'Berserk and The Band of the Hawk',
  'LEGO Worlds',
  'Ultra Street Fighter II: The Final Challengers',
  'Pokken Tournament DX',
  'Rain World',
  'Sundered',
  'The Escapists 2',
  'Total War: Warhammer II',
  'Life is Strange: Before the Storm - Episode 2: Brave New World',
  'Mr. Shifty',
  'Madden NFL 18',
  'Portal Knights',
  '1-2-Switch',
  'Toukiden 2',
  'Last Day of June',
  "Super Lucky's Tale",
  'Horizon Zero Dawn Complete Edition',
  'Snipperclips',
  'Hey! Pikmin',
  'Micro Machines World Series',
  'Wipeout: Omega Collection',
  "Everybody's Golf",
  'Matterfall',
  'Warriors All-Stars',
  "Poochy & Yoshi's Woolly World",
  'Batman: The Enemy Within - Episode 2',
  'Pillars of Eternity: Complete Edition',
  'Ever Oasis',
  'Farpoint',
  'Ark: Survival Evolved',
  'Hello Neighbor',
  'Fast RMX',
  'Monster Hunter Generations Ultimate',
  'The Long Dark',
  'Bridge Constructor Portal',
  'Hob',
  'The LEGO Ninjago Movie Video Game',
  'Digimon World: Next Order',
  'Black Mirror',
  'Windjammers',
  'The Elder Scrolls Online: Morrowind',
  'Immortal Redneck',
  'Life Is Strange: Before the Storm - Episode 3: Hell Is Empty',
  'Death Squared',
  'Dark Souls',
  'Fear Effect Sedna',
  'Disgaea 5 Complete',
  'Kingdom Hearts HD 1.5 + 2.5 ReMIX',
  'Everything',
  'Doom VFR',
  'Miitopia (3DS Edition)',
  'Has Been Heroes',
  'Fade to Silence',
  'Gorogoa',
  'Monster Hunter Stories (2024)',
  'The Disney Afternoon Collection',
  'Songbringer',
  'The Walking Dead: A New Frontier - Episode 3 - Above the Law',
  'Nights of Azure 2: Bride of the New Moon',
  "Mario & Luigi: Superstar Saga + Bowser's Minions",
  'Full Throttle: Remastered',
  'Aven Colony',
  'Tokyo 42',
  'Friday the 13th: The Game',
  'Miitopia',
  'The Walking Dead: A New Frontier - Episode 4 - Thicker Than Water',
  'FlatOut 4: Total Insanity',
  'Endless Space 2',
  'Life is Strange: Before the Storm',
  'Flinthook',
  'The Elder Scrolls V: Skyrim VR',
  'Black The Fall',
  'The Walking Dead: A New Frontier - Episode 5 - From the Gallows',
  'Golf Story',
  'Batman: The Enemy Within - Episode 3',
  'Minecraft',
  'DUSK',
  'Sine Mora EX',
  'Darkwood',
  'Wulverblade',
  'World to the West',
  'Senran Kagura: Peach Beach Splash',
  'Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings',
  'Hidden Agenda',
  'AER: Memories of Old',
  'Rogue Trooper Redux',
  'Guilty Gear Xrd REV 2',
  'ECHO',
  'Warriors Orochi 4',
  'Shining Resonance Refrain',
  'Donut County',
  'The Swords of Ditto',
  'BattleTech',
  'GRIP: Combat Racing',
  'Sword Art Online: Fatal Bullet',
  'Monster Boy and the Cursed Kingdom',
  'BlazBlue: Cross Tag Battle',
  'Shenmue 1 & 2',
  'Where the Water Tastes Like Wine',
  'Detective Pikachu',
  'Mulaka',
  'The Walking Dead: The Final Season - Episode 1',
  'Surviving Mars',
  'Earth Defense Force 5',
  'The World Ends With You: Final Remix',
  'SEGA Mega Drive Classics',
  'Phantom Doctrine',
  'BELOW',
  'LEGO The Incredibles',
  'Omensight',
  'Iconoclasts',
  "Dragon's Crown Pro",
  'Insurgency: Sandstorm',
  'The Council - Episode 1: The Mad Ones',
  'Agony',
  'Ashen',
  'Madden NFL 19',
  'Planet Alpha',
  'Return of the Obra Dinn',
  "Sid Meier's Civilization VI - Console Edition",
  'Subnautica',
  'City of Brass',
  'State of Mind',
  'Astro Bot Rescue Mission',
  'The Red Strings Club',
  'Transference',
  'Naruto to Boruto: Shinobi Striker',
  "Assassin's Creed Rogue Remastered",
  'InnerSpace',
  'Persona Dancing: Endless Night Collection',
  'Q.U.B.E. 2',
  "Death's Gambit",
  'Battle Princess Madelyn',
  '11-11: Memories Retold',
  'Gravel',
  'The Inpatient',
  'WarioWare Gold',
  'SNK 40th Anniversary Collection',
  'Little Dragons Cafe',
  "Sid Meier's Civilization VI: Rise and Fall",
  'Horizon Chase Turbo',
  'Ys: Memories of Celceta',
  'NBA 2K Playgrounds 2',
  'The Station',
  'Sushi Striker: The Way of Sushido',
  'Fist of the North Star: Lost Paradise',
  'Age of Empires: Definitive Edition',
  'Street Fighter V: Arcade Edition',
  "Luigi's Mansion",
  "Luigi's Mansion 2",
  'The Blackout Club',
  'This Is the Police 2',
  'Monster Energy Supercross: The Official Videogame',
  'Little Witch Academia: Chamber of Time',
  'Batman: The Enemy Within - Episode 4',
  'Castlevania Requiem: Symphony of the Night & Rondo of Blood',
  "Digimon Story: Cyber Sleuth - Hacker's Memory",
  'Devil May Cry HD Collection',
  'Masters of Anima',
  'Shadows: Awakening',
  'Smoke and Sacrifice',
  'Déraciné',
  'FOX n FORESTS',
  'Radiant Historia: Perfect Chronology',
  'Wandersong',
  'Lumines Remastered',
  'Warhammer 40,000: Mechanicus',
  'Life Is Strange 2 - Episode 3: Wastelands',
  "Marvel's Spider-Man: The Heist",
  'Tesla vs Lovecraft',
  'The Fall Part 2: Unbound',
  'Warhammer 40,000: Inquisitor - Martyr',
  "The Bard's Tale IV: Barrows Deep",
  'UNDER NIGHT IN-BIRTH Exe:Late[st]',
  'Golf Club: Wasteland',
  'Sinner: Sacrifice for Redemption',
  'V-Rally 4',
  'Past Cure',
  'The Adventure Pals',
  'My Memory of Us',
  'Penny-Punching Princess',
  'NHL 19',
  'Disgaea 1 Complete',
  'Earth Defense Force: Iron Rain',
  'Ni no Kuni: Wrath of the White Witch Remastered',
  'F1 2019',
  'Planet Zoo',
  'Blazing Chrome',
  'Deliver Us The Moon',
  'Arise: A simple story',
  'Final Fantasy VIII Remastered',
  'Daymare: 1998',
  'Generation Zero',
  'Afterparty',
  'MechWarrior 5: Mercenaries',
  'Moons of Madness',
  'Anno 1800',
  'SteamWorld Quest: Hand of Gilgamech',
  'Void Bastards',
  "New Super Lucky's Tale",
  'Super Monkey Ball: Banana Blitz HD',
  'Plants vs Zombies: Battle for Neighborville',
  'Sniper Ghost Warrior Contracts',
  'WRC 8',
  'Super Meat Boy Forever',
  'Sniper Elite V2 Remastered',
  'Ghostbusters: The Video Game Remastered',
  'Metal Wolf Chaos XD',
  'River City Girls',
  'Hunt: Showdown',
  'Atelier Ryza: Ever Darkness & the Secret Hideout',
  'Pikuniku',
  'Silent Hill',
  'Creature in the Well',
  'Tekken 4',
  'Tekken 5',
  'Tekken 6',
  'Dangerous Driving',
  'Slay The Spire',
  'Age of Empires II: Definitive Edition',
  'The Occupation',
  'Left Alive',
  'Sparklite',
  'WWE 2K20',
  'The Witcher',
  'Sayonara Wild Hearts',
  'Unruly Heroes',
  'Life Is Strange 2 - Episode 2: Rules',
  'Etherborn',
  'Spirit of the North',
  'The LEGO Movie 2 Videogame',
  'Ring Fit Adventure',
  'Telling Lies',
  'Genesis Alpha One',
  'Green Hell',
  'Lost Ember',
  'Song of Horror Complete',
  'GYLT',
  'KILL la KILL - IF',
  'Terminator: Resistance',
  'Manifold Garden',
  'AI: The Somnium Files',
  "Kirby's Extra Epic Yarn",
  'The Ninja Saviors: Return of the Warriors',
  'Madden NFL 20',
  'Gato Roboto',
  'Phoenix Point',
  'Erica',
  'Bubble Bobble 4 Friends',
  "Assassin's Creed III Remastered",
  'Cat Quest II',
  'Draugen',
  'What the Golf?',
  'Night Call',
  'Avicii Invector',
  'Valfaris',
  'Attack on Titan 2: Final Battle',
  'Trover Saves the Universe',
  'They Are Billions',
  'Death end re;Quest',
  'YIIK: A Postmodern RPG',
  'The Caligula Effect: Overdose',
  'Contra: Rogue Corps',
  'Atelier Lulua: The Scion of Arland',
  'Overwatch - Switch',
  'Pathologic 2',
  'Warsaw',
  'Outward',
  'Blacksad: Under the Skin',
  'NHL 20',
  'Power Rangers: Battle For The Grid',
  "Heaven's Vault",
  'Neo Cab',
  'SolSeraph',
  'Wolfenstein: Cyberpilot',
  'Persona Q2: New Cinema Labyrinth',
  'Roguebook',
  'Knights and Bikes',
  'Castlevania Anniversary Collection',
  'Fate/Extella Link',
  'Stranger Things 3: The Game',
  "Fell Seal: Arbiter's Mark",
  'SUPERHOT: MIND CONTROL DELETE',
  'Beyond Blue',
  'WWE 2K Battlegrounds',
  'Spelunky 2',
  'WRC 9 FIA World Rally Championship',
  "My Hero One's Justice 2",
  'Hood: Outlaws & Legends',
  'Tetris Effect: Connected',
  'Haven',
  'SnowRunner',
  'Chronos: Before The Ashes',
  'Skully',
  'Summer in Mara',
  'Röki',
  'Shantae and the Seven Sirens',
  'Empire of Sin',
  'Final Fantasy: Crystal Chronicles Remastered Edition',
  'Kentucky Route Zero: The Complete Season',
  'Beyond a Steel Sky',
  'Ary and the Secret of Seasons',
  'The Suicide of Rachel Foster',
  'Lost Words: Beyond the Page',
  'BPM: Bullets Per Minute',
  'Rune Factory 4 Special',
  'Fuser',
  'Devil May Cry 5: Special Edition',
  'Bloodroots',
  'EA Sports UFC 4',
  'Brigandine: The Legend of Runersia',
  'Samurai Jack: Battle Through Time',
  'Cloudpunk',
  'Those Who Remain',
  'Othercide',
  'Paradise Killer',
  'Star Renegades',
  'Iron Harvest',
  'Sword Art Online: Alicization Lycoris',
  'Age of Empires III: Definitive Edition',
  'West of Dead',
  'Rocket Arena',
  'Torchlight III',
  'Puyo Puyo Tetris 2',
  'Ride 4',
  'Bayonetta & Vanquish 10th Anniversary Bundle',
  'Command & Conquer Remastered Collection',
  'Clubhouse Games: 51 Worldwide Classics',
  'Mega Man Zero/ZX Legacy Collection',
  'Madden NFL 21',
  'Disaster Report 4: Summer Memories',
  'Valorant',
  'Necrobarista',
  'Need for Speed: Hot Pursuit Remastered',
  'South of the Circle',
  'Mafia II: Definitive Edition',
  'The Dark Crystal: Age of Resistance Tactics',
  'Curse of the Dead Gods',
  'AO Tennis 2',
  'Skater XL',
  'Control: AWE',
  'The Division',
  'The Division 2',
  'MotoGP 20',
  'Rock of Ages 3: Make & Break',
  'Tennis World Tour 2',
  'Hatsune Miku: Project DIVA Mega Mix',
  'Kunai',
  'Hotshot Racing',
  'In Other Waters',
  'Mario Kart Live: Home Circuit',
  'Crysis Remastered',
  'Remothered: Broken Porcelain',
  'MLB The Show 20',
  'Control: The Foundation',
  'Raji: An Ancient Epic',
  'The Complex',
  'Going Under',
  'Neon Abyss',
  'Peaky Blinders: Mastermind',
  'Call of Duty: Modern Warfare 2 Remastered Campaign',
  'Fight Crab',
  'Kingdom Hearts III: ReMind',
  'Spellbreak',
  'Sam & Max Save The World Remastered',
  'Genshin Impact',
  'Fury Unleashed',
  'Coffee Talk',
  '9 Monkeys of Shaolin',
  'Nexomon: Extinction',
  'The Walking Dead: Saints & Sinners',
  'Skul: The Hero Slayer',
  'No More Heroes',
  'Neversong',
  'A Total War Saga: TROY',
  'Foregone',
  'Submerged: Hidden Depths',
  'Liberated',
  'Hardspace: Shipbreaker',
  'Disc Room',
  'Capcom Arcade Stadium',
  'Legend of Mana',
  'Knockout City',
  'Greak: Memories of Azur',
  'Unpacking',
  'WRC 10',
  'Big Brain Academy: Brain vs. Brain',
  'Blue Reflection: Second Light',
  'Crysis Remastered Trilogy',
  'Destruction AllStars',
  'Subnautica: Below Zero',
  'Edge of Eternity',
  'Tails of Iron',
  'Humankind',
  'Chicory: A Colorful Tale',
  'Final Fantasy Pixel Remaster',
  'Astria Ascending',
  'The Good Life',
  'SkateBIRD',
  'Maquette',
  'MLB The Show 21',
  'PowerWash Simulator',
  'Last Stop',
  'Narita Boy',
  'EVERSPACE 2',
  'Ruined King: A League of Legends Story',
  'Disgaea 6: Defiance of Destiny',
  'Olympic Games Tokyo 2020 - The Official Video Game',
  'FORECLOSED',
  'Pathfinder: Wrath of the Righteous',
  'Voice of Cards: The Isle Dragon Roars',
  'In Sound Mind',
  'Gamedec',
  'Lake',
  'Madden NFL 22',
  'Gods Will Fall',
  'Game Builder Garage',
  'R-Type Final 2',
  'Aragami 2',
  'Vampire Survivors',
  'King of Seas',
  'SaGa Frontier Remastered',
  'Rustler',
  'Omno',
  'Young Souls',
  'Backbone',
  'Football Manager 2022',
  'Shovel Knight Pocket Dungeon',
  'Blue Fire',
  'Neptunia X Senran Kagura: Ninja Wars',
  'Before Your Eyes',
  'TOEM',
  'Demon Turf',
  "Cruis'n Blast",
  'The Caligula Effect 2',
  'JETT: The Far Shore',
  "Akiba's Trip: Hellbound & Debriefed",
  'Nioh 2 - The Complete Edition',
  'Kaze and the Wild Masks',
  'GRIME',
  'Boomerang X',
  'Genesis Noir',
  'MotoGP 21',
  'Eldest Souls',
  'Doki Doki Literature Club Plus!',
  'Final Fantasy V Pixel Remaster',
  'Axiom Verge 2',
  'Cozy Grove',
  'El Shaddai: Ascension of the Metatron',
  'Mundaun',
  'Actraiser Renaissance',
  'Paradise Lost',
  'Quake',
  'The Legend of Nayuta: Boundless Trails',
  'Earth Defense Force: World Brothers',
  'Where the Heart Leads',
  'Monster Rancher 1 & 2 DX',
  "A Juggler's Tale",
  'RiMS Racing',
  'Virtua Fighter 5: Ultimate Showdown',
  'Mighty Goose',
  'NHL 22',
  'Disjunction',
  'Moonglow Bay',
  'Poison Control',
  'Final Fantasy IV Pixel Remaster',
  'Final Fantasy III Pixel Remaster',
  'Cotton Reboot!',
  'Wavetale',
  'Say No! More',
  'REMNANT II',
  'Kitaria Fables',
  'The Nioh Collection',
  'Final Fantasy II Pixel Remaster',
  'Hoa',
  'Aeterna Noctis',
  'Turrican Flashback',
  'Ghostbusters: Spirits Unleashed',
  'Klonoa Phantasy Reverie Series',
  'Star Ocean: The Divine Force',
  'FAR: Changing Tides',
  'AI: THE SOMNIUM FILES - nirvanA Initiative',
  'Valkyrie Elysium',
  'Card Shark',
  'Salt and Sacrifice',
  "Babylon's Fall",
  'The Legend of Heroes: Trails from Zero',
  'Pac-Man World Re-Pac',
  'The Chant',
  'Dolmen',
  'Forza Horizon 2',
  'Chained Echoes',
  'Grounded',
  'Endling: Extinction is Forever',
  'Dragon Quest Treasures',
  'Moss: Book II',
  'DNF Duel',
  'Madden NFL 23',
  'MADiSON',
  'Capcom Arcade 2nd Stadium',
  'Infernax',
  'Harvestella',
  "JoJo's Bizarre Adventure: All-Star Battle R",
  'Shovel Knight Dig',
  'THE HOUSE OF THE DEAD: Remake',
  'Atari 50: The Anniversary Celebration',
  'MultiVersus',
  'Goat Simulator 3',
  'Persona 4 Arena Ultimax',
  'Cursed to Golf',
  'Fobia - St. Dinfna Hotel',
  'PGA Tour 2K23',
  'The Knight Witch',
  'SD Gundam: Battle Alliance',
  'Asterigos: Curse of the Stars',
  'Citizen Sleeper',
  'Redout 2',
  'Dragon Ball: The Breakers',
  'Expeditions: Rome',
  'The Centennial Case: A Shijima Story',
  'Tinykin',
  'Lost Ark',
  'Mario Kart 8 Deluxe: Booster Course Pass',
  'Souldiers',
  'Midnight Fight Express',
  'Arcade Paradise',
  'ANNO: Mutationem',
  'Potion Permit',
  'F1 Manager 2022',
  'River City Girls 2',
  'A Little to the Left',
  'Moonscars',
  'The Stanley Parable: Ultra Deluxe',
  'Warhammer 40,000: Chaos Gate - Daemonhunters',
  "Kirby's Dream Buffet",
  'Victoria 3',
  'Syberia: The World Before',
  'Coromon',
  'The Cruel King and the Great Hero',
  'Loot River',
  'Grapple Dog',
  'NHL 23',
  'Diablo Immortal',
  'Disney Dreamlight Valley',
  'Serious Sam: Siberian Mayhem',
  'Silt',
  'Made in Abyss: Binary Star Falling into Darkness',
  'BLACKTAIL',
  'We Are OFK',
  'Yurukill: The Calumniation Games',
  'The Entropy Centre',
  'MotoGP 22',
  'Phantom Breaker: Omnia',
  'Shredders',
  'Wonder Boy Collection',
  'MX vs ATV Legends',
  'The Last Oricru',
  'Final Fantasy VI Pixel Remaster',
  'Beacon Pines',
  'Wayward Strand',
  'Teardown',
  'Hard West 2',
  'Mount and Blade',
  'Mount and Blade: Warband',
  'Pupperazzi',
  'Serial Cleaners',
  'Way of the Hunter',
  'Matchpoint - Tennis Championships',
  "Nobunaga's Ambition: Awakening",
  'Sunday Gold',
  'Batora: Lost Haven',
  'Temtem',
  'Eternal Threads',
  'A Memoir Blue',
  'Touken Ranbu Warriors',
  'Star Ocean: The Second Story R',
  'Red Dead Redemption',
  'Resident Evil 4: Separate Ways',
  'The Expanse: A Telltale Series',
  'Mega Man Battle Network Legacy Collection',
  'The Legend of Heroes: Trails into Reverie',
  'Cities: Skylines 2',
  'A Space for the Unbound',
  'F1 23',
  'Warhammer 40,000: Rogue Trader',
  'Fae Farm',
  'Sherlock Holmes The Awakened',
  'After Us',
  'Shadow Gambit: The Cursed Crew',
  'The Legend of Heroes: Trails to Azure',
  'Ready or Not',
  'House Flipper 2',
  'Granblue Fantasy Versus: Rising',
  'Venba',
  'Have a Nice Death',
  'Atelier Marie Remake: The Alchemist of Salburg',
  'Vengeful Guardian: Moonrider',
  'Deliver Us Mars',
  'Hellboy Web of Wyrd',
  'SteamWorld Build',
  'Song of Nunu: A League of Legends Story',
  'Story of Seasons: A Wonderful Life',
  'Miasma Chronicles',
  'Crash Team Rumble',
  'MLB The Show 23',
  'Trepang2',
  'Road 96: Mile 0',
  'Jagged Alliance 3',
  'Moving Out 2',
  'Crime Boss: Rockay City',
  'Strayed Lights',
  'Terra Nil',
  'Park Beyond',
  'Fear The Spotlight',
  'Naruto X Boruto Ultimate Ninja Storm Connections',
  'Tales of Symphonia Remastered',
  'Humanity',
  'The Cosmic Wheel Sisterhood',
  'Disgaea 7: Vows of the Virtueless',
  'Harmony: The Fall of Reverie',
  'The Last Case of Benedict Fox',
  'Chants of Sennaar',
  'Eternights',
  'LONE RUIN',
  'The Mageseeker: A League of Legends Story',
  'EA Sports PGA Tour',
  'Undisputed',
  'Bomb Rush Cyberfunk',
  'Trine 5: A Clockwork Conspiracy',
  'Dragon Quest Monsters:  The Dark Prince',
  'Madden NFL 24',
  'EA Sports UFC 5',
  'Samba de Amigo: Party Central',
  'My Time at Sandrock',
  'Sonic Origins Plus',
  'The Last Faith',
  'Mato Anomalies',
  'PARANORMASIGHT: The Seven Mysteries of Honjo',
  'Trinity Trigger',
  'We Love Katamari REROLL+ Royal Reverie',
  'El Paso, Elsewhere',
  'Endless Dungeon',
  'Etrian Odyssey Origins Collection',
  'Total War: PHARAOH',
  'WrestleQuest',
  'Bramble: The Mountain King',
  'Afterimage',
  'Nickelodeon All-Star Brawl 2',
  'Ravenlok',
  'Cassette Beasts',
  'Football Manager 2024',
  'CONVERGENCE: A League of Legends Story',
  'A Highland Song',
  'Tin Hearts',
  'Wizard With A Gun',
  'Grim Guardians: Demon Purge',
  'Daymare: 1994 Sandcastle',
  'Starship Troopers: Extermination',
  'The Lord of the Rings: Return to Moria',
  'World of Horror',
  'American Arcadia',
  'Silent Hope',
  '9 Years of Shadows',
  'Under the Waves',
  'Infinity Strash: Dragon Quest The Adventure of Dai',
  'GrimGrimoire OnceMore',
  'Born of Bread',
  'CRYMACHINA',
  'Gangs of Sherwood',
  'Puzzle Bobble: Everybubble!',
  "Thank Goodness You're Here",
  'Cat Quest III',
  'Marvel Rivals',
  'Brothers: A Tale of Two Sons Remake',
  'Ultros',
  'Harold Halibut',
  'The Legend of Heroes: Trails Through Daybreak',
  'Dungeons of Hinterberg',
  'Little Kitty, Big City',
  "Mighty Morphin Power Rangers: Rita's Rewind",
  'Lorelei and the Laser Eyes',
  'Shin chan: Shiro and the Coal Town',
  'Ara: History Untold',
  'Beyond Good & Evil: 20th Anniversary Edition',
  'FAIRY TAIL 2',
  'Harry Potter: Quidditch Champions',
  'Nine Sols',
  "Sorry We're Closed",
  'Berserk Boy',
  'Alien: Rogue Incursion Evolved Edition',
  'Caravan SandWitch',
  'Enotria: The Last Song',
  'Star Wars: Battlefront Classic Collection',
  'Test Drive Unlimited Solar Crown',
  'Expeditions: A Mudrunner Game',
  "Penny's Big Breakaway",
  'Open Roads',
  'Planet Coaster 2',
  'F1 24',
  'Metro Awakening',
  'Star Wars: Bounty Hunter',
  'Starfield: Shattered Space',
  'Botany Manor',
  'Tetris Forever',
  'Dustborn',
  'REYNATIS',
  'Teenage Mutant Ninja Turtles Arcade: Wrath of the Mutants',
  'Castlevania Dominus Collection',
  'MULLET MADJACK',
  'EA Sports College Football 25',
  'Turnip Boy Robs A Bank',
  'Shadow of the Ninja - Reborn',
  'XDefiant',
  'Nikoderiko: The Magical World',
  'MLB The Show 24',
  'CYGNI: All Guns Blazing',
  'Broken Roads',
  'Creatures of Ava',
  'Bo: Path of the Teal Lotus',
  'Empire of the Ants',
  'Copycat',
  'Squirrel with a Gun',
  'Broken Sword - Shadow of the Templars: Reforged',
  'Zenless Zone Zero',
  'Batman: Arkham Shadow',
  'Infinity Nikki',
  'Arranger: A Role-Puzzling Adventure',
  'Gundam Breaker 4',
  'Killer Klowns from Outer Space: The Game',
  'Madden NFL 25',
  'Shiren the Wanderer: The Mystery Dungeon of Serpentcoil Island',
  'The Cub',
  'Wild Bastards',
  'Europa',
  'Phantom Fury',
  'Lil Guardsman',
  'Bakeru',
  'Snufkin: Melody of Moominvalley',
  'Bandle Tale: A League of Legends Story',
  'Riven',
  'ANTONBLAST',
  'Momodora: Moonlit Farewell',
  'Gori: Cuddly Carnage',
  'Capes',
  'Earth Defense Force 6',
  'Paper Trail',
  'CONSCRIPT',
  'The Smurfs: Dreams',
  'Clock Tower: Rewind',
  'Yars Rising',
  'Star Wars: Dark Forces Remaster',
  'Duck Detective: The Secret Salami',
  'Homeworld 3',
  'The Thing: Remastered',
  'Alan Wake 2: The Lake House',
  'Monster Jam Showdown',
  'Slave Zero X',
  "Mika and the Witch's Mountain",
  'Alan Wake 2: Night Springs',
  'MechWarrior 5: Clans',
  '#BLUD',
  'Until Then',
  'Tomba! Special Edition',
  'Farming Simulator 25',
  'Highwater',
];
